[profile.default]
src = "eth-contracts/src"
out = "eth-contracts/out"
libs = ["eth-contracts/lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.20"
via-ir = true

remappings = [
    "@eigenlayer-middleware/=eth-contracts/lib/eigenlayer-middleware/",
    "@eigenlayer-contracts/=eth-contracts/lib/eigenlayer-contracts/",
    "@openzeppelin-contracts/=eth-contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-contracts-upgradeable/=eth-contracts/lib/openzeppelin-contracts-upgradeable/",
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4