[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_limit = "18446744073709551615"
memory_limit = 18446744073709
evm_version = "paris"
# ignore compiler warning: unused-param
ignored_error_codes = [5667]
# ignore warnings from script folder and test folder
ignored_warnings_from = ["script", "test"]
# fail compilation if the warnings are not fixed.
# this is super useful for the code size warning.
deny_warnings = true
# optimization is no longer enabled by default
optimizer = true
optimizer_runs = 200
solc = "0.8.28"

remappings = [
    "@createx/=lib/createx/",
    "@interop/=lib/interop-lib/src/",
    
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/openzeppelin-contracts-upgradeable/",

    "@layerzero-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/",
    
    "forge-std/=lib/forge-std/src/",

    "solady/=lib/solady"

]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"
imua = "${IMUA_RPC_URL}"
op_sepolia = "${OPSEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"


[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
