[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.30"
via-ir = true  # Re-enabled to fix stack too deep error
optimizer = true
optimizer_runs = 200
evm_version = "london"  # This should prevent PUSH0 even with via-ir

remappings = [
    "@createx/=lib/createx/",
    "@interop/=lib/interop-lib/src/",
    
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/openzeppelin-contracts-upgradeable/",
    
    "forge-std/=lib/forge-std/src/",

]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"
imua = "${IMUA_RPC_URL}"
op_sepolia = "${OPSEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"


[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
